// 地区
const araeList = [
  {
    title: 'A',
    list: [
      {
        id: 1,
        label: '安庆',
      },
      {
        id: 1,
        label: '澳门',
      },
      {
        id: 1,
        label: '阿里',
      },
      {
        id: 1,
        label: '安康',
      },
    ],
  },
  {
    title: 'B',
    list: [
      {
        id: 2,
        label: '北京',
      },
      {
        id: 3,
        label: '保定',
      },
      {
        id: 4,
        label: '宝鸡',
      },
      {
        id: 5,
        label: '北海',
      },
      {
        id: 6,
        label: '包头',
      },
    ],
  },
  {
    title: 'C',
    list: [
      {
        id: 2,
        label: '重庆',
      },
      {
        id: 3,
        label: '杭州',
      },
      {
        id: 4,
        label: '成都',
      },
      {
        id: 5,
        label: '昌江',
      },
      {
        id: 6,
        label: '苏州',
      },
    ],
  },
  {
    title: 'D',
    list: [
      {
        id: 2,
        label: '大连',
      },
      {
        id: 3,
        label: '大理市',
      },
    ],
  },
  {
    title: 'E',
    list: [
      {
        id: 2,
        label: '九江',
      },
      {
        id: 3,
        label: '济南',
      },
    ],
  },
  {
    title: 'F',
    list: [
      {
        id: 2,
        label: '九江',
      },
      {
        id: 3,
        label: '济南',
      },
    ],
  },
  {
    title: 'J',
    list: [
      {
        id: 2,
        label: '九江',
      },
      {
        id: 3,
        label: '济南',
      },
    ],
  },
];

// 产品列表
const productList = [
  {
    id: 0,
    img: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw50iwj20ff0aaaci.jpg',
    title: '贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透',
    tip: 0,
    num: 399,
    collagelist: [
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw1k2wj20p00goq7n.jpg',
      },
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw50iwj20ff0aaaci.jpg',
      },
    ],
  },
  {
    id: 1,
    img: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw1k2wj20p00goq7n.jpg',
    title: '贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透',
    tip: 1,
    num: 599,
    collagelist: [
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw1k2wj20p00goq7n.jpg',
      },
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vvsr72j20p00gogo2.jpg',
      },
    ],
  },
  {
    id: 2,
    img: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw50iwj20ff0aaaci.jpg',
    title: '贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透',
    tip: 0,
    num: 799,
    collagelist: [
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw1k2wj20p00goq7n.jpg',
      },
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw50iwj20ff0aaaci.jpg',
      },
    ],
  },
  {
    id: 0,
    img: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw50iwj20ff0aaaci.jpg',
    title: '贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透',
    tip: 0,
    num: 399,
    collagelist: [
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw1k2wj20p00goq7n.jpg',
      },
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw50iwj20ff0aaaci.jpg',
      },
    ],
  },
  {
    id: 1,
    img: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw1k2wj20p00goq7n.jpg',
    title: '贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透',
    tip: 1,
    num: 599,
    collagelist: [
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw1k2wj20p00goq7n.jpg',
      },
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vvsr72j20p00gogo2.jpg',
      },
    ],
  },
  {
    id: 2,
    img: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw50iwj20ff0aaaci.jpg',
    title: '贵州黄果树+西江千户苗寨+荔波5日4晚跟团游·【平台惠选·纯玩时代】买得起·游得爽 贵阳2晚连住·不挪窝 亲子含早+透',
    tip: 0,
    num: 799,
    collagelist: [
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw1k2wj20p00goq7n.jpg',
      },
      {
        url: 'https://ww1.sinaimg.cn/large/663d3650gy1fq66vw50iwj20ff0aaaci.jpg',
      },
    ],
  },
];

const priceMoreDate = [
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-01 00:00:00',
    weekDay: 5,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-02 00:00:00',
    weekDay: 6,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-03 00:00:00',
    weekDay: 0,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-04 00:00:00',
    weekDay: 1,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-05 00:00:00',
    weekDay: 2,
  },
  {
    id: 12,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-06 00:00:00',
    weekDay: 3,
  },
  {
    id: 1,
    productId: 2,
    singlePrice: 12,
    groupSinglePrice: 12,
    groupKidsPrice: 12,
    kidsPrice: 12,
    stockQty: 12,
    soldQty: 12,
    status: 1,
    date: '2018-06-07 00:00:00',
    weekDay: 4,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-08 00:00:00',
    weekDay: 5,
  },
  {
    id: 13,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-09 00:00:00',
    weekDay: 6,
  },
  {
    id: 14,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-10 00:00:00',
    weekDay: 0,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-11 00:00:00',
    weekDay: 1,
  },
  {
    id: 15,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-12 00:00:00',
    weekDay: 2,
  },
  {
    id: 16,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-13 00:00:00',
    weekDay: 3,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-14 00:00:00',
    weekDay: 4,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-15 00:00:00',
    weekDay: 5,
  },
  {
    id: 17,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-16 00:00:00',
    weekDay: 6,
  },
  {
    id: 18,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-17 00:00:00',
    weekDay: 0,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-18 00:00:00',
    weekDay: 1,
  },
  {
    id: 19,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-19 00:00:00',
    weekDay: 2,
  },
  {
    id: 20,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-20 00:00:00',
    weekDay: 3,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-21 00:00:00',
    weekDay: 4,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-22 00:00:00',
    weekDay: 5,
  },
  {
    id: 21,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-23 00:00:00',
    weekDay: 6,
  },
  {
    id: 22,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-24 00:00:00',
    weekDay: 0,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-25 00:00:00',
    weekDay: 1,
  },
  {
    id: 23,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-26 00:00:00',
    weekDay: 2,
  },
  {
    id: 24,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-27 00:00:00',
    weekDay: 3,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-28 00:00:00',
    weekDay: 4,
  },
  {
    id: 0,
    productId: null,
    singlePrice: null,
    groupSinglePrice: null,
    groupKidsPrice: null,
    kidsPrice: null,
    stockQty: null,
    soldQty: null,
    status: null,
    date: '2018-06-29 00:00:00',
    weekDay: 5,
  },
  {
    id: 25,
    productId: 2,
    singlePrice: 654,
    groupSinglePrice: 654,
    groupKidsPrice: 645,
    kidsPrice: 654,
    stockQty: 6546,
    soldQty: null,
    status: null,
    date: '2018-06-30 00:00:00',
    weekDay: 6,
  },
];

export default {
  araeList,
  productList,
  priceMoreDate,
};
